using System;
using System.Collections.Generic;

namespace NatoliOrderInterface.Models.NAT01
{
    public partial class OrderHeader
    {
        public double OrderNo { get; set; }
        public string CustomerNo { get; set; }
        public string ShipToAccountNo { get; set; }
        public string ShipToNo { get; set; }
        public short? LastLineNo { get; set; }
        public short? LastNoteNo { get; set; }
        public DateTime? OrderDate { get; set; }
        public double? OrderMarkdown { get; set; }
        public double? OrderSubtotal { get; set; }
        public double? OrderFreightCharge { get; set; }
        public double? OrderTax { get; set; }
        public double? OrderTotal { get; set; }
        public string Ponumber { get; set; }
        public string Poextension { get; set; }
        public string ShippedVia { get; set; }
        public string SalesRepId { get; set; }
        public string TermsId { get; set; }
        public string Purpose { get; set; }
        public string PrintOrderStatus { get; set; }
        public string PostedtoGpasyn { get; set; }
        public string ShippedYn { get; set; }
        public string Note1 { get; set; }
        public string Note2 { get; set; }
        public string ShiptoName { get; set; }
        public string ShiptoAddr1 { get; set; }
        public string ShiptoAddr2 { get; set; }
        public string ShiptoAddr3 { get; set; }
        public string ShiptoCity { get; set; }
        public string ShiptoState { get; set; }
        public string ShiptoZip { get; set; }
        public string ShiptoCountry { get; set; }
        public DateTime? RequestedShipDate { get; set; }
        public string ShiptoPhone { get; set; }
        public string ShiptoFax { get; set; }
        public short? LastWonoteNo { get; set; }
        public string PrintOrderAckStat { get; set; }
        public string PrintHobTicketStatus { get; set; }
        public string PrintPkgSlipStat { get; set; }
        public string PrintMiniWorkOrd { get; set; }
        public string AlreadyPrintedWo { get; set; }
        public string PrintMisc2 { get; set; }
        public string HardSoft { get; set; }
        public string Priority { get; set; }
        public string ShippingBillMethod { get; set; }
        public string ProductName { get; set; }
        public string HobRequired { get; set; }
        public short? LastRemake { get; set; }
        public string WorkOrderType { get; set; }
        public string EngineeringNote1 { get; set; }
        public string EngineeringNote2 { get; set; }
        public string MiscNote { get; set; }
        public string EtchingNote { get; set; }
        public string ShippingNote { get; set; }
        public string InspectionNote { get; set; }
        public string Email { get; set; }
        public string InternationalId { get; set; }
        public string EmailName { get; set; }
        public string Email2 { get; set; }
        public string Email2Name { get; set; }
        public string Email3 { get; set; }
        public string Email3Name { get; set; }
        public string Email4 { get; set; }
        public string Email4Name { get; set; }
        public string Email5 { get; set; }
        public string Email5Name { get; set; }
        public string UnitOfMeasure { get; set; }
        public string Itnrequired { get; set; }
        public string CommInvType { get; set; }
        public string Incoterms { get; set; }
        public string ShippingAcctNo { get; set; }
        public string DutiesTaxesBilling { get; set; }
        public string ExportReason { get; set; }
        public string LogisticsContact { get; set; }
        public string LogisticsEmail { get; set; }
        public DateTime? OrigShipDate { get; set; }
        public short? WorkOrderPrintQty { get; set; }
        public bool? QtyAlreadyUpdated { get; set; }
        public string ExportedtoProE { get; set; }
        public double? QuoteNumber { get; set; }
        public short? QuoteRevNo { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPhoneNo { get; set; }
        public string ShipWithWono { get; set; }
        public string OnHold { get; set; }
        public DateTime? RequestedShipDateRev { get; set; }
        public string Revision { get; set; }
        public string ExportYorN { get; set; }
        public string PrintComments1 { get; set; }
        public string PrintComments2 { get; set; }
        public string Shape { get; set; }
        public string RushYorN { get; set; }
        public string RushNatoliContact { get; set; }
        public string NatoliContact { get; set; }
        public string InternationalYorN { get; set; }
        public string NewCustomer { get; set; }
        public string LogisticsPhoneNo { get; set; }
        public string Itnno { get; set; }
        public int? OriginalWo { get; set; }
        public string DutiesTaxesAcctNo { get; set; }
        public string RestrictShipment { get; set; }
        public string CurrencyId { get; set; }
        public double? ExchangeRate { get; set; }
        public string RestrictShipmentDesc { get; set; }
        public string ShippingAmountFixed { get; set; }
        public string UserStampCreated { get; set; }
        public string UserStampModified { get; set; }
        public string Uetching1 { get; set; }
        public string Uetching2 { get; set; }
        public string Uetching3 { get; set; }
        public string Uetching4 { get; set; }
        public string Uetching5 { get; set; }
        public string Uetching6 { get; set; }
        public string Letching1 { get; set; }
        public string Letching2 { get; set; }
        public string Letching3 { get; set; }
        public string Letching4 { get; set; }
        public string Letching5 { get; set; }
        public string Letching6 { get; set; }
        public string Detching1 { get; set; }
        public string Detching2 { get; set; }
        public string Detching3 { get; set; }
        public string Detching4 { get; set; }
        public string Detching5 { get; set; }
        public string Detching6 { get; set; }
        public string Retching1 { get; set; }
        public string Retching2 { get; set; }
        public string Retching3 { get; set; }
        public string Retching4 { get; set; }
        public string Retching5 { get; set; }
        public string Retching6 { get; set; }
        public string UserAcctNo { get; set; }
        public string UserLocNo { get; set; }
        public string Uetching1B { get; set; }
        public string Uetching2B { get; set; }
        public string Uetching3B { get; set; }
        public string Uetching4B { get; set; }
        public string Uetching5B { get; set; }
        public string Uetching6B { get; set; }
        public string Letching1B { get; set; }
        public string Letching2B { get; set; }
        public string Letching3B { get; set; }
        public string Letching4B { get; set; }
        public string Letching5B { get; set; }
        public string Letching6B { get; set; }
        public string Detching1B { get; set; }
        public string Detching2B { get; set; }
        public string Detching3B { get; set; }
        public string Detching4B { get; set; }
        public string Detching5B { get; set; }
        public string Detching6B { get; set; }
        public string Retching1B { get; set; }
        public string Retching2B { get; set; }
        public string Retching3B { get; set; }
        public string Retching4B { get; set; }
        public string Retching5B { get; set; }
        public string Retching6B { get; set; }
        public string Aetching1 { get; set; }
        public string Aetching2 { get; set; }
        public string Aetching3 { get; set; }
        public string Aetching4 { get; set; }
        public string Aetching5 { get; set; }
        public string Aetching6 { get; set; }
        public string Uetching7 { get; set; }
        public string Letching7 { get; set; }
        public string Detching7 { get; set; }
        public string Retching7 { get; set; }
        public string Uetching7B { get; set; }
        public string Letching7B { get; set; }
        public string Detching7B { get; set; }
        public string Retching7B { get; set; }
        public string Aetching7 { get; set; }
        public bool? Tm2data { get; set; }
        public int? ProjectNo { get; set; }
        public string DrawingSetNo { get; set; }
        public string ShipToContact { get; set; }
        public string Aetching8 { get; set; }
        public string Aetching9 { get; set; }
        public string Aetching10 { get; set; }
        public string ShipToTaxRegNo { get; set; }
        public string SoldToTaxRegNo { get; set; }
        public string UserTaxRegNo { get; set; }
        public string DrawingPo { get; set; }
        public string Reference { get; set; }
        public string Email6 { get; set; }
        public string Email6Name { get; set; }
        public string Email7 { get; set; }
        public string Email7Name { get; set; }
        public string Email8 { get; set; }
        public string Email8Name { get; set; }
        public string CommInvAddlComments { get; set; }
        public string PrintVenPkSlip { get; set; }
        public string ShipperQuoteNo { get; set; }
        public int? RefWo { get; set; }
        public string PaidRushFee { get; set; }
    }
}
